name: egrimod-nem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=18.2.0=py_0
  - backcall=0.1.0=py_0
  - basemap=1.2.0=py36h6c86909_1000
  - bleach=3.0.2=py_0
  - boost=1.66.0=py36_vc14_1
  - boost-cpp=1.66.0=vc14_1
  - ca-certificates=2018.10.15=ha4d7672_0
  - click=7.0=py_0
  - click-plugins=1.0.4=py_0
  - cligj=0.5.0=py_0
  - colorama=0.4.0=py_0
  - curl=7.60.0=vc14_0
  - cycler=0.10.0=py_1
  - decorator=4.3.0=py_0
  - descartes=1.1.0=py_2
  - entrypoints=0.2.3=py36_1002
  - expat=2.2.5=vc14_0
  - fiona=1.7.13=py36h2fc6367_4
  - freetype=2.8.1=vc14_0
  - freexl=1.0.2=vc14_2
  - gdal=2.2.4=py36h2fc6367_1
  - geopandas=0.4.0=py_1
  - geos=3.6.2=he025d50_3
  - geotiff=1.4.2=vc14_1
  - hdf4=4.2.13=vc14_0
  - hdf5=1.10.1=vc14_2
  - icu=58.2=vc14_0
  - ipykernel=5.1.0=py36h39e3cac_1001
  - ipython=7.1.1=py36h39e3cac_1000
  - ipython_genutils=0.2.0=py_1
  - jedi=0.13.1=py36_1000
  - jinja2=2.10=py_1
  - jpeg=9b=vc14_2
  - jsonschema=3.0.0a3=py36_1000
  - jupyter_client=5.2.3=py_1
  - jupyter_core=4.4.0=py_0
  - kealib=1.4.7=vc14_4
  - kiwisolver=1.0.1=py36he980bc4_1002
  - krb5=1.14.6=vc14_0
  - libgdal=2.2.4=vc14_5
  - libiconv=1.14=vc14_4
  - libnetcdf=4.6.1=vc14_2
  - libpng=1.6.34=vc14_0
  - libpq=9.6.3=vc14_0
  - libsodium=1.0.16=vc14_0
  - libspatialindex=1.8.5=vc14_1
  - libspatialite=4.3.0a=vc14_19
  - libssh2=1.8.0=hc4dcbb0_2
  - libtiff=4.0.9=vc14_0
  - libxml2=2.9.5=vc14_1
  - markupsafe=1.1.0=py36hfa6e2cd_1000
  - matplotlib=2.2.2=py36_1
  - mistune=0.8.4=py36hfa6e2cd_1000
  - mkl_fft=1.0.6=py36_0
  - mkl_random=1.0.2=py36_0
  - munch=2.3.2=py_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.2.0=py36_1000
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - notebook=5.7.2=py36_1000
  - openjpeg=2.3.0=vc14_2
  - openssl=1.0.2o=vc14_0
  - pandas=0.23.4=py36h830ac7b_1000
  - pandoc=2.3.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pickleshare=0.7.5=py36_1000
  - proj4=4.9.3=vc14_5
  - prometheus_client=0.4.2=py_0
  - prompt_toolkit=2.0.7=py_0
  - psycopg2=2.7.5=py36h74b6da3_1
  - pygments=2.2.0=py_1
  - pyparsing=2.3.0=py_0
  - pyproj=1.9.5.1=py36haf3c679_1006
  - pyqt=5.6.0=py36h764d66f_7
  - pyrsistent=0.14.6=py36hfa6e2cd_1000
  - pysal=1.14.4.post2=py36_1001
  - pyshp=2.0.0=py_0
  - python-dateutil=2.7.5=py_0
  - pytz=2018.7=py_0
  - pywinpty=0.5.4=py36_1002
  - pyzmq=17.1.2=py36hf576995_1001
  - qt=5.6.2=vc14_1
  - rtree=0.8.3=py36_1000
  - send2trash=1.5.0=py_0
  - shapely=1.6.4=py36hc90234e_1000
  - sip=4.18.1=py36h6538335_0
  - six=1.11.0=py36_1001
  - sqlalchemy=1.2.14=py36hfa6e2cd_1000
  - sqlite=3.20.1=vc14_2
  - terminado=0.8.1=py36_1001
  - testpath=0.4.2=py36_1000
  - tornado=5.1.1=py36hfa6e2cd_1000
  - traitlets=4.3.2=py36_1000
  - vc=14=0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - winpty=0.4.3=4
  - xerces-c=3.2.0=vc14_0
  - xz=5.2.4=h2fa13f4_1001
  - zeromq=4.2.5=vc14_2
  - zlib=1.2.11=vc14_0
  - blas=1.0=mkl
  - certifi=2018.10.15=py36_0
  - icc_rt=2017.0.4=h97af966_0
  - intel-openmp=2019.1=144
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2018.0.3=1
  - msys2-conda-epoch=20160418=1
  - numpy=1.15.4=py36ha559c80_0
  - numpy-base=1.15.4=py36h8128ebf_0
  - pip=18.1=py36_0
  - python=3.6.5=h0c2934d_0
  - scipy=1.1.0=py36h4f6bf74_1
  - setuptools=40.6.2=py36_0
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wheel=0.32.3=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - appdirs==1.4.3
    - branca==0.3.1
    - chardet==3.0.4
    - folium==0.7.0
    - idna==2.7
    - kml2geojson==4.0.2
    - nose==1.3.7
    - ply==3.11
    - pyomo==5.5.1
    - pyutilib==5.6.3
    - requests==2.20.1
    - urllib3==1.24.1
    - xlrd==1.1.0
prefix: C:\Users\eee\Anaconda3\envs\egrimod-nem-env

